// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Sentrisense
//
//! Configuration loaded from environment variables.
//!
//! All settings have sensible defaults so only the NATS stream/consumer names
//! are strictly required for the bridge to start.

use std::env;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InputTransport {
    Nats,
    UnixSocket,
}

impl InputTransport {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Nats => "nats",
            Self::UnixSocket => "unix_socket",
        }
    }

    fn parse(value: &str) -> anyhow::Result<Self> {
        match value {
            "nats" => Ok(Self::Nats),
            "unix_socket" => Ok(Self::UnixSocket),
            other => Err(anyhow::anyhow!(
                "INPUT_TRANSPORT must be one of: nats, unix_socket (got '{other}')"
            )),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Config {
    // ── Input transport ────────────────────────────────────────────────────────
    /// Upstream message transport used to feed the bridge.
    pub input_transport: InputTransport,

    // ── NATS ──────────────────────────────────────────────────────────────────
    /// NATS server URL (default: `nats://localhost:4222`). Used only in NATS mode.
    pub nats_url: String,
    /// JetStream stream to subscribe to (required in NATS mode).
    pub nats_stream: String,
    /// Durable consumer name on that stream (required in NATS mode).
    pub nats_consumer: String,
    /// Optional subject filter applied at subscription time.
    /// When set, only messages published on this subject are processed.
    pub nats_subject_filter: Option<String>,
    /// Path to a NATS credentials file (`.creds`) for JWT/NKey authentication.
    ///
    /// Generated by the `nsc` tool.  When set, the bridge authenticates with
    /// the NATS server using the embedded JWT + NKey seed rather than with an
    /// unauthenticated connection.
    ///
    /// Set via `NATS_CREDENTIALS`.
    pub nats_credentials_path: Option<String>,

    // ── Unix socket input ─────────────────────────────────────────────────────
    /// Filesystem path for the local Unix domain socket listener.
    pub unix_socket_path: String,
    /// Optional effective UID allowed to connect to the Unix socket.
    pub unix_socket_allowed_uid: Option<u32>,
    /// Optional effective GID allowed to connect to the Unix socket.
    pub unix_socket_allowed_gid: Option<u32>,
    /// Maximum request line size accepted from the Unix socket transport.
    pub unix_socket_max_line_bytes: usize,

    // ── IEC-104 server ────────────────────────────────────────────────────────
    /// Network address for the IEC-104 server to bind on (default: `0.0.0.0`)
    pub iec104_bind_addr: String,
    /// TCP port for the IEC-104 server (default: `2404`)
    pub iec104_port: u16,
    /// Default Common Address (ASDU address) when not supplied in the JSON
    /// message (default: `1`)
    pub iec104_default_ca: u16,

    // ── Observability ─────────────────────────────────────────────────────────
    /// TCP port for the Prometheus metrics HTTP endpoint (default: `9091`).
    ///
    /// Set via the `METRICS_PORT` environment variable.
    pub metrics_port: u16,

    // ── TLS / IEC 62351-3 ────────────────────────────────────────────────────
    /// Enable Mutual TLS (IEC 62351-3 compliant transport security).
    ///
    /// When `true` the bridge starts a TLS listener on [`Self::tls_port`] and
    /// requires all three certificate paths to be set.  The `lib60870` server
    /// is automatically re-bound to loopback so that only the TLS listener
    /// accepts external connections.
    ///
    /// Set via `TLS_ENABLED=true` (default: `false`).
    pub tls_enabled: bool,
    /// Path to the server's PEM-encoded certificate chain.
    ///
    /// Required when `tls_enabled = true`.  Set via `TLS_CERT_PATH`.
    pub tls_cert_path: Option<String>,
    /// Path to the server's PEM-encoded private key.
    ///
    /// Required when `tls_enabled = true`.  Set via `TLS_KEY_PATH`.
    pub tls_key_path: Option<String>,
    /// Path to the PEM-encoded Root CA certificate used to verify **client**
    /// certificates (Mutual TLS).
    ///
    /// Required when `tls_enabled = true`.  Set via `TLS_CA_CERT_PATH`.
    pub tls_ca_cert_path: Option<String>,
    /// TCP port for the external TLS listener (default: `19998`).
    ///
    /// Port 19998 is the IANA-registered port for IEC 62351-3 secured IEC-104.
    /// Set via `TLS_PORT`.
    pub tls_port: u16,
}

type NatsConfigParts = (String, String, String, Option<String>, Option<String>);
type UnixSocketConfigParts = (String, Option<u32>, Option<u32>, usize);
type ServerConfigParts = (String, u16, u16, u16);
type TlsConfigParts = (bool, Option<String>, Option<String>, Option<String>, u16);

struct ConfigParts {
    input_transport: InputTransport,
    nats: NatsConfigParts,
    unix_socket: UnixSocketConfigParts,
    server: ServerConfigParts,
    tls: TlsConfigParts,
}

impl Config {
    /// Build a [`Config`] by reading environment variables.
    ///
    /// # Errors
    /// Returns an error if required variables for the selected transport are missing.
    pub fn from_env() -> anyhow::Result<Self> {
        Self::from_lookup(|key| env::var(key).ok())
    }

    /// Build a [`Config`] from an arbitrary key–value lookup.
    ///
    /// The lookup closure mirrors `std::env::var`: return `Some(value)` when
    /// the key is present, `None` otherwise.
    ///
    /// This variant is the testable entry-point; production code should call
    /// [`Self::from_env`] which delegates here with the real environment.
    ///
    /// # Errors
    /// Returns an error if required settings for the selected transport are absent,
    /// or if numeric configuration values cannot be parsed.
    pub fn from_lookup<F>(get: F) -> anyhow::Result<Self>
    where
        F: Fn(&str) -> Option<String>,
    {
        let parts = Self::load_config_parts(&get)?;
        let (nats_url, nats_stream, nats_consumer, nats_subject_filter, nats_credentials_path) =
            parts.nats;
        let (
            unix_socket_path,
            unix_socket_allowed_uid,
            unix_socket_allowed_gid,
            unix_socket_max_line_bytes,
        ) = parts.unix_socket;
        let (iec104_bind_addr, iec104_port, iec104_default_ca, metrics_port) = parts.server;
        let (tls_enabled, tls_cert_path, tls_key_path, tls_ca_cert_path, tls_port) = parts.tls;

        Ok(Self {
            input_transport: parts.input_transport,
            nats_url,
            nats_stream,
            nats_consumer,
            nats_subject_filter,
            nats_credentials_path,
            unix_socket_path,
            unix_socket_allowed_uid,
            unix_socket_allowed_gid,
            unix_socket_max_line_bytes,
            iec104_bind_addr,
            iec104_port,
            iec104_default_ca,
            metrics_port,
            tls_enabled,
            tls_cert_path,
            tls_key_path,
            tls_ca_cert_path,
            tls_port,
        })
    }

    fn load_config_parts<F>(get: &F) -> anyhow::Result<ConfigParts>
    where
        F: Fn(&str) -> Option<String>,
    {
        let input_transport = Self::load_input_transport(get)?;

        Ok(ConfigParts {
            input_transport,
            nats: Self::load_nats_config(get, input_transport)?,
            unix_socket: Self::load_unix_socket_config(get)?,
            server: Self::load_server_config(get)?,
            tls: Self::load_tls_config(get)?,
        })
    }

    fn load_input_transport<F>(get: &F) -> anyhow::Result<InputTransport>
    where
        F: Fn(&str) -> Option<String>,
    {
        InputTransport::parse(&get("INPUT_TRANSPORT").unwrap_or_else(|| "nats".into()))
    }

    fn load_nats_config<F>(
        get: &F,
        input_transport: InputTransport,
    ) -> anyhow::Result<NatsConfigParts>
    where
        F: Fn(&str) -> Option<String>,
    {
        let nats_url = get("NATS_URL").unwrap_or_else(|| "nats://localhost:4222".into());
        let (nats_stream, nats_consumer) = Self::load_nats_consumer_parts(get, input_transport)?;

        Ok((
            nats_url,
            nats_stream,
            nats_consumer,
            get("NATS_SUBJECT_FILTER"),
            get("NATS_CREDENTIALS"),
        ))
    }

    fn load_nats_consumer_parts<F>(
        get: &F,
        input_transport: InputTransport,
    ) -> anyhow::Result<(String, String)>
    where
        F: Fn(&str) -> Option<String>,
    {
        match input_transport {
            InputTransport::Nats => Ok((
                Self::required(get, "NATS_STREAM")?,
                Self::required(get, "NATS_CONSUMER")?,
            )),
            InputTransport::UnixSocket => Ok((String::new(), String::new())),
        }
    }

    fn load_unix_socket_config<F>(get: &F) -> anyhow::Result<UnixSocketConfigParts>
    where
        F: Fn(&str) -> Option<String>,
    {
        let unix_socket_max_line_bytes = Self::load_unix_socket_max_line_bytes(get)?;

        Ok((
            get("UNIX_SOCKET_PATH").unwrap_or_else(|| "/run/iec104bridge/input.sock".into()),
            Self::parse_optional(get, "UNIX_SOCKET_ALLOWED_UID")?,
            Self::parse_optional(get, "UNIX_SOCKET_ALLOWED_GID")?,
            unix_socket_max_line_bytes,
        ))
    }

    fn load_unix_socket_max_line_bytes<F>(get: &F) -> anyhow::Result<usize>
    where
        F: Fn(&str) -> Option<String>,
    {
        let max_line_bytes = Self::parse_with_default(get, "UNIX_SOCKET_MAX_LINE_BYTES", "65536")?;
        if max_line_bytes == 0 {
            anyhow::bail!("UNIX_SOCKET_MAX_LINE_BYTES must be greater than zero");
        }

        Ok(max_line_bytes)
    }

    fn load_server_config<F>(get: &F) -> anyhow::Result<ServerConfigParts>
    where
        F: Fn(&str) -> Option<String>,
    {
        Ok((
            get("IEC104_BIND_ADDR").unwrap_or_else(|| "0.0.0.0".into()),
            Self::parse_with_default(get, "IEC104_PORT", "2404")?,
            Self::parse_with_default(get, "IEC104_CA", "1")?,
            Self::parse_with_default(get, "METRICS_PORT", "9091")?,
        ))
    }

    fn load_tls_config<F>(get: &F) -> anyhow::Result<TlsConfigParts>
    where
        F: Fn(&str) -> Option<String>,
    {
        let tls_enabled = Self::is_truthy(get("TLS_ENABLED"));
        let tls_cert_path = get("TLS_CERT_PATH");
        let tls_key_path = get("TLS_KEY_PATH");
        let tls_ca_cert_path = get("TLS_CA_CERT_PATH");

        Self::validate_tls_paths(
            tls_enabled,
            &tls_cert_path,
            &tls_key_path,
            &tls_ca_cert_path,
        )?;

        Ok((
            tls_enabled,
            tls_cert_path,
            tls_key_path,
            tls_ca_cert_path,
            Self::parse_with_default(get, "TLS_PORT", "19998")?,
        ))
    }

    fn required<F>(get: &F, key: &str) -> anyhow::Result<String>
    where
        F: Fn(&str) -> Option<String>,
    {
        get(key).ok_or_else(|| anyhow::anyhow!("{key} must be set"))
    }

    fn require_present(value: &Option<String>, key: &str) -> anyhow::Result<()> {
        if value.is_none() {
            anyhow::bail!("{key} must be set when TLS_ENABLED=true");
        }
        Ok(())
    }

    fn validate_tls_paths(
        tls_enabled: bool,
        tls_cert_path: &Option<String>,
        tls_key_path: &Option<String>,
        tls_ca_cert_path: &Option<String>,
    ) -> anyhow::Result<()> {
        if !tls_enabled {
            return Ok(());
        }

        for (value, key) in [
            (tls_cert_path, "TLS_CERT_PATH"),
            (tls_key_path, "TLS_KEY_PATH"),
            (tls_ca_cert_path, "TLS_CA_CERT_PATH"),
        ] {
            Self::require_present(value, key)?;
        }

        Ok(())
    }

    fn is_truthy(value: Option<String>) -> bool {
        value
            .map(|v| v.to_lowercase())
            .map(|v| v == "true" || v == "1" || v == "yes")
            .unwrap_or(false)
    }

    fn parse_optional<F, T>(get: &F, key: &str) -> anyhow::Result<Option<T>>
    where
        F: Fn(&str) -> Option<String>,
        T: std::str::FromStr,
    {
        get(key)
            .map(|value| {
                value.parse::<T>().map_err(|_| {
                    anyhow::anyhow!("{key} must be a valid {}", std::any::type_name::<T>())
                })
            })
            .transpose()
    }

    fn parse_with_default<F, T>(get: &F, key: &str, default: &str) -> anyhow::Result<T>
    where
        F: Fn(&str) -> Option<String>,
        T: std::str::FromStr,
    {
        get(key)
            .unwrap_or_else(|| default.into())
            .parse::<T>()
            .map_err(|_| anyhow::anyhow!("{key} must be a valid {}", std::any::type_name::<T>()))
    }
}

// ─── tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::{Config, InputTransport};
    use std::collections::HashMap;

    /// Build a Config from a static key–value map.
    fn from_map(map: &HashMap<&str, &str>) -> anyhow::Result<Config> {
        Config::from_lookup(|key| map.get(key).map(|v| v.to_string()))
    }

    fn required() -> HashMap<&'static str, &'static str> {
        let mut m = HashMap::new();
        m.insert("NATS_STREAM", "sensors");
        m.insert("NATS_CONSUMER", "bridge");
        m
    }

    // ── required fields ───────────────────────────────────────────────────────

    #[test]
    fn missing_nats_stream_is_error() {
        let mut map = required();
        map.remove("NATS_STREAM");
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn missing_nats_consumer_is_error() {
        let mut map = required();
        map.remove("NATS_CONSUMER");
        assert!(from_map(&map).is_err());
    }

    // ── defaults ──────────────────────────────────────────────────────────────

    #[test]
    fn default_nats_url() {
        let cfg = from_map(&required()).unwrap();
        assert_eq!(cfg.nats_url, "nats://localhost:4222");
    }

    #[test]
    fn default_input_transport_is_nats() {
        let cfg = from_map(&required()).unwrap();
        assert_eq!(cfg.input_transport, InputTransport::Nats);
    }

    #[test]
    fn default_iec104_port() {
        let cfg = from_map(&required()).unwrap();
        assert_eq!(cfg.iec104_port, 2404);
    }

    #[test]
    fn default_iec104_ca() {
        let cfg = from_map(&required()).unwrap();
        assert_eq!(cfg.iec104_default_ca, 1);
    }

    #[test]
    fn default_bind_addr() {
        let cfg = from_map(&required()).unwrap();
        assert_eq!(cfg.iec104_bind_addr, "0.0.0.0");
    }

    #[test]
    fn default_subject_filter_is_none() {
        let cfg = from_map(&required()).unwrap();
        assert_eq!(cfg.nats_subject_filter, None);
    }

    #[test]
    fn default_unix_socket_settings() {
        let cfg = from_map(&required()).unwrap();
        assert_eq!(cfg.unix_socket_path, "/run/iec104bridge/input.sock");
        assert_eq!(cfg.unix_socket_allowed_uid, None);
        assert_eq!(cfg.unix_socket_allowed_gid, None);
        assert_eq!(cfg.unix_socket_max_line_bytes, 65_536);
    }

    // ── overrides ─────────────────────────────────────────────────────────────

    #[test]
    fn custom_nats_url() {
        let mut map = required();
        map.insert("NATS_URL", "nats://nats.example.com:4222");
        let cfg = from_map(&map).unwrap();
        assert_eq!(cfg.nats_url, "nats://nats.example.com:4222");
    }

    #[test]
    fn custom_iec104_port() {
        let mut map = required();
        map.insert("IEC104_PORT", "12345");
        let cfg = from_map(&map).unwrap();
        assert_eq!(cfg.iec104_port, 12345);
    }

    #[test]
    fn custom_iec104_ca() {
        let mut map = required();
        map.insert("IEC104_CA", "42");
        let cfg = from_map(&map).unwrap();
        assert_eq!(cfg.iec104_default_ca, 42);
    }

    #[test]
    fn custom_subject_filter() {
        let mut map = required();
        map.insert("NATS_SUBJECT_FILTER", "plant.a.>");
        let cfg = from_map(&map).unwrap();
        assert_eq!(cfg.nats_subject_filter, Some("plant.a.>".into()));
    }

    #[test]
    fn custom_bind_addr() {
        let mut map = required();
        map.insert("IEC104_BIND_ADDR", "127.0.0.1");
        let cfg = from_map(&map).unwrap();
        assert_eq!(cfg.iec104_bind_addr, "127.0.0.1");
    }

    #[test]
    fn unix_socket_transport_does_not_require_nats_settings() {
        let mut map = HashMap::new();
        map.insert("INPUT_TRANSPORT", "unix_socket");
        let cfg = from_map(&map).unwrap();
        assert_eq!(cfg.input_transport, InputTransport::UnixSocket);
        assert_eq!(cfg.nats_stream, "");
        assert_eq!(cfg.nats_consumer, "");
    }

    #[test]
    fn custom_unix_socket_settings() {
        let mut map = HashMap::new();
        map.insert("INPUT_TRANSPORT", "unix_socket");
        map.insert("UNIX_SOCKET_PATH", "/tmp/test.sock");
        map.insert("UNIX_SOCKET_ALLOWED_UID", "123");
        map.insert("UNIX_SOCKET_ALLOWED_GID", "456");
        map.insert("UNIX_SOCKET_MAX_LINE_BYTES", "4096");

        let cfg = from_map(&map).unwrap();
        assert_eq!(cfg.unix_socket_path, "/tmp/test.sock");
        assert_eq!(cfg.unix_socket_allowed_uid, Some(123));
        assert_eq!(cfg.unix_socket_allowed_gid, Some(456));
        assert_eq!(cfg.unix_socket_max_line_bytes, 4096);
    }

    // ── parse errors ──────────────────────────────────────────────────────────

    #[test]
    fn invalid_input_transport_is_error() {
        let mut map = required();
        map.insert("INPUT_TRANSPORT", "redis");
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn invalid_port_is_error() {
        let mut map = required();
        map.insert("IEC104_PORT", "not_a_number");
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn invalid_unix_socket_uid_is_error() {
        let mut map = HashMap::new();
        map.insert("INPUT_TRANSPORT", "unix_socket");
        map.insert("UNIX_SOCKET_ALLOWED_UID", "abc");
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn zero_unix_socket_max_line_bytes_is_error() {
        let mut map = HashMap::new();
        map.insert("INPUT_TRANSPORT", "unix_socket");
        map.insert("UNIX_SOCKET_MAX_LINE_BYTES", "0");
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn port_out_of_u16_range_is_error() {
        let mut map = required();
        map.insert("IEC104_PORT", "99999");
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn invalid_ca_is_error() {
        let mut map = required();
        map.insert("IEC104_CA", "not_a_number");
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn stream_and_consumer_are_stored() {
        let cfg = from_map(&required()).unwrap();
        assert_eq!(cfg.nats_stream, "sensors");
        assert_eq!(cfg.nats_consumer, "bridge");
    }

    // ── TLS / IEC 62351-3 ─────────────────────────────────────────────────────

    #[test]
    fn tls_disabled_by_default() {
        let cfg = from_map(&required()).unwrap();
        assert!(!cfg.tls_enabled);
        assert_eq!(cfg.tls_port, 19998);
        assert!(cfg.tls_cert_path.is_none());
        assert!(cfg.tls_key_path.is_none());
        assert!(cfg.tls_ca_cert_path.is_none());
    }

    #[test]
    fn tls_enabled_requires_cert_path() {
        let mut map = required();
        map.insert("TLS_ENABLED", "true");
        map.insert("TLS_KEY_PATH", "/key.pem");
        map.insert("TLS_CA_CERT_PATH", "/ca.pem");
        // TLS_CERT_PATH missing
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn tls_enabled_requires_key_path() {
        let mut map = required();
        map.insert("TLS_ENABLED", "true");
        map.insert("TLS_CERT_PATH", "/cert.pem");
        map.insert("TLS_CA_CERT_PATH", "/ca.pem");
        // TLS_KEY_PATH missing
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn tls_enabled_requires_ca_cert_path() {
        let mut map = required();
        map.insert("TLS_ENABLED", "true");
        map.insert("TLS_CERT_PATH", "/cert.pem");
        map.insert("TLS_KEY_PATH", "/key.pem");
        // TLS_CA_CERT_PATH missing
        assert!(from_map(&map).is_err());
    }

    #[test]
    fn tls_enabled_with_all_paths_ok() {
        let mut map = required();
        map.insert("TLS_ENABLED", "true");
        map.insert("TLS_CERT_PATH", "/cert.pem");
        map.insert("TLS_KEY_PATH", "/key.pem");
        map.insert("TLS_CA_CERT_PATH", "/ca.pem");
        let cfg = from_map(&map).unwrap();
        assert!(cfg.tls_enabled);
        assert_eq!(cfg.tls_cert_path, Some("/cert.pem".into()));
        assert_eq!(cfg.tls_key_path, Some("/key.pem".into()));
        assert_eq!(cfg.tls_ca_cert_path, Some("/ca.pem".into()));
    }

    #[test]
    fn tls_enabled_truthy_values() {
        for val in &["true", "1", "yes", "True", "TRUE", "YES"] {
            let mut map = required();
            map.insert("TLS_ENABLED", val);
            map.insert("TLS_CERT_PATH", "/c.pem");
            map.insert("TLS_KEY_PATH", "/k.pem");
            map.insert("TLS_CA_CERT_PATH", "/ca.pem");
            let cfg = from_map(&map).unwrap();
            assert!(
                cfg.tls_enabled,
                "Expected tls_enabled=true for TLS_ENABLED={val}"
            );
        }
    }

    #[test]
    fn custom_tls_port() {
        let mut map = required();
        map.insert("TLS_PORT", "8883");
        let cfg = from_map(&map).unwrap();
        assert_eq!(cfg.tls_port, 8883);
    }
}
